# Change these first
owner: euro # Your GitHub username
repo: status # Your Github repository name

# Add your sites here
sites:
  - name: USFA Akamai
    url: https://www.usfa.fema.gov
  - name: USFA Apps
    url: https://apps.usfa.fema.gov
  - name: USFA NFA
    url: https://nfa.usfa.fema.gov
  - name: Civilian fatalities
    url: https://apps.usfa.fema.gov/civilian-fatalities
  - name: Contact - NFA courses voucher
    url: https://apps.usfa.fema.gov/contact/voucher
  - name: Contact - Register for Fire is Everyones Fight materials
    url: https://apps.usfa.fema.gov/contact/fief
  - name: Contact - Qualitative feedback on analytical reports
    url: https://apps.usfa.fema.gov/contact/dataReportEval
  - name: Contact - NFIRS tech support form
    url: https://apps.usfa.fema.gov/contact/ntsc
  - name: Contact - Credly badge request
    url: https://apps.usfa.fema.gov/contact/credlyBadge
  - name: Contact - Library research consultation request
    url: https://apps.usfa.fema.gov/contact/researchConsult
  - name: Fire department registry
    url: https://apps.usfa.fema.gov/registry
  - name: Firefighter fatalities
    url: https://apps.usfa.fema.gov/firefighter-fatalities
  - name: Hotel/Motel
    url: https://apps.usfa.fema.gov/hotel
  - name: Hotel/Motel state management
    url: https://apps.usfa.fema.gov/hotel/state_management
  - name: NFAcourses
    url: https://apps.usfa.fema.gov/nfacourses
  - name: NFAcourses - Instructor
    url: https://apps.usfa.fema.gov/nfacourses/instructor
  - name: NFAcourses - Course call
    url: https://apps.usfa.fema.gov/nfacourses/courseCall
  - name: NFAcourses - Distance learning evaluation
    url: https://apps.usfa.fema.gov/nfacourses/DistanceLearningEvaluation
  - name: NFAcourses - End of course evaluation
    url: https://apps.usfa.fema.gov/nfacourses/eoc
  - name: NFAcourses - Long term evaluation
    url: https://apps.usfa.fema.gov/nfacourses/longTermEvaluation
  - name: Publications
    url: https://apps.usfa.fema.gov/publications
  - name: Thesaurus
    url: https://apps.usfa.fema.gov/thesaurus

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /status
  logoUrl: https://static1.squarespace.com/static/594131ea86e6c04a5926a83d/t/5a2dc732f9619a5b7c8c583c/1552582183328/?format=1500w
  name: clutch monitor
  introTitle: "**We makes complex things simple.**"
  introMessage: A general status page that checks for http response headers every five minutes.
i18n:
  footer: This page is made with ❤️ by euro.

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
